name: CI

on:
  push:
    branches:
      - main

env:
  TRAVIS_BUILD_DIR: /home/runner/work/ansible-thoteam.nexus3-oss

jobs:
  lint:
    name: Checking overall syntax (groovy, yaml, python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Run linting
        run: |
          ./tests/test_groovySyntax.sh
          molecule test

  test-centos7:
    name: Test on centos7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Run tests on centos7
        run: molecule test -s default-centos7

  test-debian-bullseye:
    name: Test on Debian Bullseye
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Run tests on Debian Bullseye
        run: molecule test -s default-debian_bullseye
branches:
  only:
    - main

sudo: required

language: python

python: 3.9

cache:
  pip: true
  directories:
    - molecule/.nexus-downloads/

env:
  global:
    TRAVIS_BUILD_DIR: /home/travis/build/ansible-thoteam.nexus3-oss

services:
  - docker

before_install:
  - cd ..
  - mv nexus3-oss $TRAVIS_BUILD_DIR
  - cd ..
  - rmdir ansible-ThoTeam
  - cd $TRAVIS_BUILD_DIR

install:
  - pip install --upgrade --upgrade-strategy eager -r requirements.txt

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: Checking overall syntax (groovy, yaml, python)
      script: |-
        ./tests/test_groovySyntax.sh
        molecule test
    - stage: test
      name: Test on centos7
      script: |-
        molecule test -s default-centos7
    - stage: test
      name: Test on Debian Bullseye
      script: |-
        molecule test -s default-debian_bullseye

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
