---
  # TODO: Skip this task if the migration is already done or postgres is already used

- name: Download the Nexus database migration tool
  get_url:
    url: "{{ nexus_db_migrator_download_url }}/nexus-db-migrator-{{ nexus_db_migrator_version }}.jar"
    dest: "{{ nexus_data_dir }}/db/nexus-db-migrator-{{ nexus_db_migrator_version }}.jar"
    mode: "0644"
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
  tags: nexus-migrate, nexus-healthcheck

- name: Enable Pro version
  ansible.builtin.include_tasks: enable_pro_version.yml
  tags: nexus-migrate, nexus-healthcheck

- name: Stop Nexus service
  ansible.builtin.systemd:
    name: nexus.service
    state: stopped
  tags: nexus-migrate, nexus-healthcheck
  when: nexus_migrate_database | default(false) | bool

- name: Healthcheck
  ansible.builtin.command:
    cmd: 'java -Xmx16G -Xms16G -XX:+UseG1GC -XX:MaxDirectMemorySize=28672M -jar nexus-db-migrator-{{ nexus_db_migrator_version }}.jar --healthcheck --yes'
    chdir: "{{ nexus_data_dir }}/db"
  become: true
  become_user: "{{ nexus_os_user }}"
  register: migration_healthcheck
  tags: nexus-migrate, nexus-healthcheck
  when: nexus_migrate_database | default(false) | bool

- debug:
    var: migration_healthcheck.stdout_lines
  tags: nexus-migrate, nexus-healthcheck
  when: nexus_migrate_database | default(false) | bool

- name: Run migration
  ansible.builtin.command:
    cmd: >
      java -Xmx16G -Xms16G -XX:+UseG1GC -XX:MaxDirectMemorySize=28672M
      -jar nexus-db-migrator-{{ nexus_db_migrator_version }}.jar --yes --tmpdir="{{ nexus_migrate_tmp_dir }}"
      --migration_type=postgres
      --db_url="jdbc:postgresql://{{ nexus_postgres_db_host }}:{{ nexus_postgres_db_port }}/{{ nexus_postgres_db_name }}?user={{ nexus_postgres_db_username }}&password={{ nexus_postgres_db_password }}"
      --content_migration="{{ nexus_migrate_content_migration }}"
      --logging.level.com.sonatype=TRACE
      --force="{{ nexus_migrate_force | bool }}"
    chdir: "{{ nexus_data_dir }}/db"
  become: true
  become_user: "{{ nexus_os_user }}"
  register: migration_result
  tags: nexus-migrate
  when: nexus_migrate_database | default(false) | bool

- debug:
    var: migration_result.stdout_lines
  tags: nexus-migrate
  when: nexus_migrate_database | default(false) | bool

- name: Set fact to enable Postgres
  set_fact:
    nexus_database_migration_done: true
  tags: nexus-migrate
  when: nexus_migrate_database | default(false) | bool

- name: Enable Postgres as datastore
  ansible.builtin.include_tasks: enable_postgres.yml
  tags: nexus-migrate
  when: nexus_migrate_database | default(false) | bool
