---
# Download database migration tool
- name: Download the Nexus database migration tool
  get_url:
    url: "https://download.sonatype.com/nexus/nxrm3-migrator/nexus-db-migrator-{{ nexus_version }}.jar"
    dest: "{{ nexus_data_dir }}/db/nexus-db-migrator-{{ nexus_version }}.jar"
    mode: "0644"
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
  tags: nexus-postgresql
