hosted_defaults:
  apt:
    blob_store: blob-apt
    online: true
    distribution: dist
    keypair: 'none'
    passphrase: 'none'
    strict_content_validation: true
    layout_policy: strict # strict or permissive
    write_policy: allow_once # one of "allow", "allow_once" or "deny"
    cleanup_policies:
      - apt_cleanup
  docker:
    online: true
    blob_store: blob-docker
    force_basic_auth: true
    strict_content_validation: true
    allow_redeploy_latest: false
    version_policy: release # release, snapshot or mixed
    write_policy: allow_once
    layout_policy: strict # strict or permissive
    http_port: null
    https_port: null
    sub_domain: ''
    v1_enabled: false
    cleanup_policies:
      - docker_cleanup
  gitlfs:
    repositoryName: <team>-repo
    recipeName: recipeName,
    online: true
    blob_store: blob-gitlfs
    layout_policy: strict # strict or permissive
    write_policy: allow_once # ALLOW_ONCE or ALLOW
    strict_content_validation: true
    cleanup_policies:
      - gitlfs_cleanup
  helm:
    repositoryName: <team>-repo
    recipeName: recipeName,
    online: true
    blob_store: blob-helm
    layout_policy: strict # strict or permissive
    write_policy: allow_once # ALLOW_ONCE or ALLOW
    strict_content_validation: true
    cleanup_policies:
      - helm_cleanup
  maven2:
    online: true
    blob_store: blob-mvn
    strict_content_validation: true
    version_policy: release # release, snapshot or mixed
    layout_policy: strict # strict or permissive
    write_policy: allow_once # one of "allow", "allow_once" or "deny"
    cleanup_policies:
      - mvn_cleanup
  npm:
    repositoryName: <team>-repo
    recipeName: recipeName,
    online: true
    blob_store: blob-npm
    layout_policy: strict # strict or permissive
    write_policy: allow_once # ALLOW_ONCE or ALLOW
    strict_content_validation: true
    cleanup_policies:
      - npm_cleanup
  nuget:
    repositoryName: <team>-repo
    recipeName: recipeName,
    online: true
    blob_store: blob-nuget
    layout_policy: strict # strict or permissive
    write_policy: allow_once # ALLOW_ONCE or ALLOW
    strict_content_validation: true
    cleanup_policies:
      - nuget_cleanup
  pypi:
    repositoryName: <team>-repo
    recipeName: recipeName,
    online: true
    blob_store: blob-pypi
    layout_policy: strict # strict or permissive
    write_policy: allow_once # ALLOW_ONCE or ALLOW
    strict_content_validation: true
    cleanup_policies:
      - python_cleanup
  raw:
    repositoryName: <team>-repo
    recipeName: recipeName,
    online: true
    blob_store: blob-raw
    layout_policy: strict # strict or permissive
    write_policy: allow_once # ALLOW_ONCE or ALLOW
    strict_content_validation: true
    cleanup_policies:
      - raw_cleanup
    contentDisposition: INLINE
  yum:
    repositoryName: <team>-repo
    recipeName: recipeName,
    online: true
    blob_store: blob-yum
    layout_policy: strict # strict or permissive
    write_policy: allow_once # ALLOW_ONCE or ALLOW
    strict_content_validation: true
    cleanup_policies:
      - yum_cleanup
    repodataDepth: 1
    deployPolicy: strict # strict or permissive

proxy_defaults:
  maven:
    - name: maven-central
      format: maven2
      online: true
      blocked: false
      auto_block: true
      remote:
        url: https://repo.maven.apache.org/maven2
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
      version_policy:
      layout_policy:
      content_disposition:
  python:
    - name: pypi-central
      format: pypi
      online: true
      blocked: false
      auto_block: true
      remote:
        url: https://pypi.org/simple
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
  npm:
    - name: npm-registry
      format: npm
      online: true
      blocked: false
      auto_block: true
      remote:
        url: https://registry.npmjs.org/
        username:
        password:
        bearerToken:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
  nuget:
    - name: nuget-gallery
      format: nuget
      online: true
      blocked: false
      auto_block: true
      nuget_version: v3
      remote:
        url: https://api.nuget.org/v3/index.json
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
  apt:
    - name: ubuntu-apt
      format: apt
      online: true
      blocked: false
      auto_block: true
      distribution: bionic
      flat: false
      remote:
        url: http://archive.ubuntu.com/ubuntu/
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
  helm:
    - name: helm-proxy
      format: helm
      online: true
      blocked: false
      auto_block: true
      remote:
        url: https://kubernetes-charts.storage.googleapis.com
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
  r:
    - name: r-proxy
      format: r
      online: true
      blocked: false
      auto_block: true
      remote:
        url: https://cran.r-project.org
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
  raw:
    - name: raw-proxy
      format: raw
      online: true
      blocked: false
      auto_block: true
      remote:
        url: https://www.jfrog.com/
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
      contentDisposition:
  conda:
    - name: conda-proxy
      format: conda
      online: true
      blocked: false
      auto_block: true
      remote:
        url: https://repo.anaconda.com/pkgs/main
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
  go:
    - name: go-proxy
      format: go
      online: true
      blocked: false
      auto_block: true
      remote:
        url: https://proxy.golang.org
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
  yum:
    - name: yum-proxy
      format: yum
      online: true
      blocked: false
      auto_block: true
      remote:
        url: http://mirror.centos.org/centos/
        username:
        password:
      connection:
        useTrustStore: false
        retries:
        user_agent_suffix:
        enable_cookies:
        enable_circular_redirects:
        timeout:
      maximum_component_age:
      maximum_metadata_age:
      negative_cache_enabled:
      negative_cache_ttl:
      cleanup_policies:
        - policy-1
group_defaults:
  maven:
  python:
