---
dependency:
  name: galaxy
  enabled: false

driver:
  name: default
  options:
    managed: True
    login_cmd_template: "docker exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: docker

platforms:
  - name: nexus3-oss-default
    hostname: nexus3-oss-default
    image: thoteam/molecule_apache_openjdk8:centos7
    command: /usr/sbin/init
    pull: true
    pre_build_image: true
    privileged: true
    groups:
      - nexus
    networks: &nexus_networks
      - name: nexus-default
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/.nexus-downloads:/nexus-downloads

  - name: slapd-server-mock
    hostname: slapd-server-mock
    image: thoteam/slapd-server-mock:latest
    override_command: false
    pull: true
    pre_build_image: true
    env:
      LDAP_DOMAIN: slapd-server-mock
    groups:
      - mockldap
    networks: *nexus_networks

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  test_sequence:
    - lint

verifier:
  name: testinfra

role_name_check: 2
