name: CI Actions
run-name: ${{ github.actor }} is testing changes
on:
  pull_request:
    types:
      [
        opened,
        reopened,
        review_requested,
        auto_merge_enabled,
        ready_for_review,
        edited,
        synchronize,
      ]
  merge_group:
    types: [checks_requested]
jobs:
  Prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.12"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run lint
        run: |
          ./tests/test_groovySyntax.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
